const {createClient}=window.supabase;
const db=createClient(window.NEXA_CONFIG.SUPABASE_URL,window.NEXA_CONFIG.SUPABASE_KEY);
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const params=new URLSearchParams(location.search),offersOnly=params.get('ofertas')==='1',initialCategorySlug=params.get('categoria')||'',initialQuery=params.get('q')||params.get('busca')||'';
let allProducts=[],categories=[],activeCategory=null,displayLimit=40;
function branding(d){if(!d)return;document.title=d.brand_name?`${d.brand_name} — Gráfica Profissional`:document.title;document.documentElement.style.setProperty('--primary',d.primary_color||'#19c7b5');document.documentElement.style.setProperty('--primary-dark',d.primary_color||'#0b9f91');document.documentElement.style.setProperty('--ink',d.text_color||'#102033');if(d.background_color)document.documentElement.style.setProperty('--white',d.background_color);document.body.style.fontFamily=d.body_font||'Inter,ui-sans-serif,system-ui,sans-serif';const mark=$('#brandMark');if(mark&&d.logo_url)mark.outerHTML=`<img id="brandMark" class="brand-logo" src="${esc(d.logo_url)}" alt="${esc(d.brand_name||'NEXA PRINT')}">`;if(d.favicon_url){let f=document.querySelector('link[rel="icon"]');if(!f){f=document.createElement('link');f.rel='icon';document.head.appendChild(f)}f.href=d.favicon_url}}
async function loadSettings(){const {data}=await db.from('site_settings').select('*').eq('id',1).maybeSingle();branding(data)}
function injectCatalogStyles(){if($('#catalogFamilyStyles'))return;const s=document.createElement('style');s.id='catalogFamilyStyles';s.textContent=`.category-nav{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff}.category-nav-inner{display:flex;align-items:center;gap:8px;min-height:48px}.category-nav-scroll{display:flex;align-items:center;gap:6px;overflow-x:auto;overflow-y:hidden;scroll-behavior:smooth;scrollbar-width:thin;flex:1;padding:5px 2px}.category-nav-scroll::-webkit-scrollbar{height:5px}.category-nav-scroll::-webkit-scrollbar-track{background:#f0f4f2;border-radius:10px}.category-nav-scroll::-webkit-scrollbar-thumb{background:#b7cbc6;border-radius:10px}.category-nav-link{flex:0 0 auto;white-space:nowrap;padding:7px 12px;border:1px solid transparent;border-radius:999px;color:var(--ink);font-size:12px;font-weight:800}.category-nav-link:hover{background:#edf7f4;border-color:#c9e1db;color:var(--primary-dark)}.category-nav-link.active{background:var(--ink);color:#fff}.category-nav-arrow{width:30px;height:30px;flex:0 0 30px;border:1px solid var(--line);border-radius:50%;background:#fff;color:var(--ink);display:grid;place-items:center;font-size:18px}.category-nav-label{flex:0 0 auto;color:var(--muted);font-size:10px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.family-badge{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;background:#e9f7f4;color:var(--primary-dark);font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.product-card.family-card{border-color:#cde3df}.product-card.family-card h3{font-size:18px}.product-card.family-card .hint{font-weight:700;color:var(--primary-dark)}@media(max-width:760px){.category-nav-label{display:none}.category-nav-arrow{display:none}.category-nav-scroll{scrollbar-width:none}.category-nav-scroll::-webkit-scrollbar{display:none}.category-nav-link{font-size:11px;padding:7px 10px}}`;document.head.appendChild(s)}
function injectCategoryNav(){injectCatalogStyles();if($('#categoryNav'))return;const nav=document.createElement('div');nav.id='categoryNav';nav.className='category-nav';nav.setAttribute('aria-label','Categorias de produtos');document.querySelector('.topbar')?.insertAdjacentElement('afterend',nav)}
function renderCategoryNav(){const nav=$('#categoryNav');if(!nav)return;nav.innerHTML='<div class="container category-nav-inner"><span class="category-nav-label">Produtos</span><button class="category-nav-arrow" type="button" data-dir="-1">‹</button><div class="category-nav-scroll" id="categoryNavScroll"><a class="category-nav-link" href="index.html#produtos">Todos</a></div><button class="category-nav-arrow" type="button" data-dir="1">›</button></div>';const scroll=$('#categoryNavScroll');scroll.insertAdjacentHTML('beforeend',(categories||[]).map(c=>`<a class="category-nav-link${norm(initialCategorySlug)===norm(c.slug)?' active':''}" href="index.html?categoria=${encodeURIComponent(c.slug)}#produtos">${esc(c.name)}</a>`).join(''));nav.querySelectorAll('.category-nav-arrow').forEach(b=>b.addEventListener('click',()=>scroll.scrollBy({left:Number(b.dataset.dir)*Math.max(240,scroll.clientWidth*.55),behavior:'smooth'})))}
async function loadCategories(){const {data,error}=await db.from('categories').select('id,name,slug,image_url,sort_order').eq('is_active',true).order('sort_order').order('name');if(error)throw error;categories=data||[];renderCategoryNav();const grid=$('#categoryGrid');if(grid)grid.innerHTML=categories.map(c=>`<a class="category-card" href="#produtos" data-category="${esc(c.id)}"><div class="category-thumb">${c.image_url?`<img src="${esc(c.image_url)}" alt="" loading="lazy">`:'<span class="muted">NEXA PRINT</span>'}</div><strong>${esc(c.name)}</strong><span>Ver produtos</span></a>`).join('');grid?.querySelectorAll('[data-category]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();activeCategory=el.dataset.category;displayLimit=40;const c=categories.find(x=>x.id===activeCategory),f=$('#activeFilter');if(f){f.textContent=c?.name||'Todos';f.classList.add('active')}renderProducts();$('#produtos')?.scrollIntoView({behavior:'smooth'})}));const match=categories.find(c=>norm(c.slug)===norm(initialCategorySlug));if(match){activeCategory=match.id;const f=$('#activeFilter');if(f){f.textContent=match.name;f.classList.add('active')}}}
async function loadProducts(){allProducts=[];for(let from=0;;from+=1000){const {data,error}=await db.from('products').select('id,name,slug,category_id,image_url,short_description,is_featured,is_offer,family_key,family_name').eq('is_active',true).order('is_featured',{ascending:false}).order('is_offer',{ascending:false}).order('name').range(from,from+999);if(error)throw error;allProducts.push(...(data||[]));if(!data||data.length<1000)break}if(initialQuery&&$('#search')){$('#search').value=initialQuery;activeCategory=null}if(offersOnly&&$('#activeFilter')){$('#activeFilter').textContent='Ofertas';$('#activeFilter').classList.add('active')}await renderProducts();if(initialQuery||offersOnly||initialCategorySlug)requestAnimationFrame(()=>$('#produtos')?.scrollIntoView({behavior:'smooth'}))}
function filtered(){const q=norm($('#search')?.value);return allProducts.filter(p=>(!offersOnly||p.is_offer)&&(!activeCategory||p.category_id===activeCategory)&&(!q||norm(`${p.name} ${p.short_description||''} ${p.family_name||''}`).includes(q)))}
function buildCards(list){const groups=new Map();for(const p of list){if(p.family_key){if(!groups.has(p.family_key))groups.set(p.family_key,{family_key:p.family_key,family_name:p.family_name||p.name,items:[]});groups.get(p.family_key).items.push(p)}else groups.set(`product:${p.id}`,{items:[p],family_key:null,family_name:null})}return [...groups.values()].map(g=>({...g,representative:g.items[0]}))}
async function startFamilyPrice(g){const ids=g.items.map(x=>x.id);if(!ids.length)return null;const {data:vs}=await db.from('product_variants').select('id').in('product_id',ids).eq('is_active',true).limit(100);const vids=(vs||[]).map(v=>v.id);if(!vids.length)return null;const {data:ps}=await db.from('variant_prices').select('selling_price,cost_price').in('variant_id',vids).order('selling_price',{ascending:true}).limit(1);const p=ps?.[0];return p?.selling_price??(p?.cost_price!=null?Number(p.cost_price)*2:null)}
async function renderProducts(){const list=filtered(),cards=buildCards(list),count=$('#catalogCount');if(count)count.textContent=`${cards.length.toLocaleString('pt-BR')} opção${cards.length===1?'':'ões'}`;$('#emptyState')?.classList.toggle('hidden',cards.length!==0);$('#catalogMore')?.classList.toggle('hidden',cards.length<=displayLimit);if($('#loadMore'))$('#loadMore').textContent=cards.length>displayLimit?`Carregar mais (${Math.min(40,cards.length-displayLimit)}+)`:'Carregar mais';if(!cards.length){$('#productGrid').innerHTML='';return}const visible=cards.slice(0,displayLimit);$('#productGrid').innerHTML=visible.map(g=>{const p=g.representative,isFamily=!!g.family_key,url=isFamily?`produto.html?family=${encodeURIComponent(g.family_key)}`:`produto.html?id=${encodeURIComponent(p.id)}`;return `<a class="product-card${isFamily?' family-card':''}" href="${url}"><div class="product-image">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(isFamily?g.family_name:p.name)}" loading="lazy">`:'<span class="image-placeholder">Imagem em breve</span>'}</div><div class="product-body">${isFamily?'<span class="family-badge">Guia de produto</span>':'<div class="cat">NEXA PRINT</div>'}<h3>${esc(isFamily?g.family_name:p.name)}</h3><div class="price" data-start="${esc(g.family_key||p.id)}">Consultando preço…</div><div class="hint">${isFamily?'Escolha tamanho, material, impressão, acabamento e gabarito em uma única página.':'Configure quantidade e acabamento'}</div>${p.is_offer&&!isFamily?'<span class="offer-badge">Oferta</span>':''}</div></a>`}).join('');await Promise.all(visible.map(async g=>{const price=await startFamilyPrice(g),el=document.querySelector(`[data-start="${CSS.escape(g.family_key||g.representative.id)}"]`);if(el)el.textContent=price!=null?`A partir de ${brl(price)}`:'Consulte as opções'}))}
$('#search')?.addEventListener('input',()=>{activeCategory=null;displayLimit=40;const f=$('#activeFilter');if(f&&!offersOnly){f.textContent='Todos';f.classList.remove('active')}clearTimeout(renderProducts.t);renderProducts.t=setTimeout(()=>renderProducts(),120)});
$('#search')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const q=$('#search').value.trim();location.href=q?`index.html?q=${encodeURIComponent(q)}#produtos`:'index.html#produtos'}});
$('#activeFilter')?.addEventListener('click',()=>{if(offersOnly){location.href='index.html#produtos';return}activeCategory=null;displayLimit=40;$('#activeFilter').textContent='Todos';$('#activeFilter').classList.remove('active');renderProducts()});
$('#loadMore')?.addEventListener('click',()=>{displayLimit+=40;renderProducts()});
(async()=>{try{injectCategoryNav();await loadSettings();await loadCategories();await loadProducts()}catch(e){console.error(e);if($('#catalogCount'))$('#catalogCount').textContent='Catálogo indisponível';$('#emptyState')?.classList.remove('hidden')}})();