const NEXA_CART_KEY='nexa_print_cart_v1';
const getCart=()=>{try{return JSON.parse(localStorage.getItem(NEXA_CART_KEY)||'[]')}catch{return[]}};
const saveCart=c=>localStorage.setItem(NEXA_CART_KEY,JSON.stringify(c));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escCart=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const labelCart=k=>({size:'Tamanho',material:'Material',printing:'Impressão',finish:'Acabamento',cut_type:'Corte'})[k]||k;
function cartCount(){return getCart().reduce((n,i)=>n+Number(i.quantity||0),0)}
function updateCartBadges(){document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cartCount());}
function readProductSelection(){const id=new URLSearchParams(location.search).get('id');const name=document.querySelector('#detail h1')?.textContent?.trim();const selects=[...document.querySelectorAll('#variantFields select')];const options=Object.fromEntries(selects.map(s=>[s.dataset.key,s.value]));const radio=document.querySelector('#quantities input[name="qty"]:checked');const qtyLabel=radio?.closest('.qty')?.querySelector('.qty-left')?.textContent?.trim()||'';const match=qtyLabel.match(/[\d.]+/);const quantity=Number((match?.[0]||'0').replace('.',''));const price=Number(radio?.dataset.price||0);if(!id||!name||!price||!quantity)return null;return {id,name,options,quantity,price,qtyLabel,key:`${id}|${JSON.stringify(options)}|${quantity}`}}
function addItem(item){const cart=getCart();const idx=cart.findIndex(x=>x.key===item.key);if(idx>=0)cart[idx].quantity+=item.quantity;else cart.push(item);saveCart(cart);updateCartBadges()}
function handleProductAction(mode){const item=readProductSelection();if(!item){alert('Selecione a configuração e a quantidade antes de continuar.');return}addItem(item);location.href='carrinho.html'+(mode==='buy'?'?checkout=1':'')}
document.addEventListener('click',e=>{const btn=e.target.closest('#cart,#buy');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();handleProductAction(btn.id==='buy'?'buy':'cart')},true);
function renderCart(){const list=document.querySelector('#cartItems');if(!list)return;const cart=getCart();const empty=document.querySelector('#cartEmpty'),checkout=document.querySelector('#checkoutBox');if(!cart.length){list.innerHTML='';empty?.classList.remove('hidden');checkout?.classList.add('hidden');document.querySelector('#cartTotal').textContent=money(0);updateCartBadges();return}empty?.classList.add('hidden');checkout?.classList.remove('hidden');list.innerHTML=cart.map((i,n)=>`<article class="cart-item"><div><span class="eyebrow">PRODUTO</span><h3>${escCart(i.name)}</h3><div class="cart-options">${Object.entries(i.options||{}).filter(([,v])=>v).map(([k,v])=>`<span>${escCart(labelCart(k))}: ${escCart(v)}</span>`).join('')}</div><strong>${escCart(i.qtyLabel||`${i.quantity} un`)}</strong></div><div class="cart-item-right"><strong>${money(i.price)}</strong><button class="remove-item" data-remove="${n}" type="button">Remover</button></div></article>`).join('');document.querySelector('#cartTotal').textContent=money(cart.reduce((s,i)=>s+Number(i.price||0),0));updateCartBadges()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;const c=getCart();c.splice(Number(b.dataset.remove),1);saveCart(c);renderCart()});
document.addEventListener('submit',e=>{if(e.target.id!=='orderForm')return;e.preventDefault();const data=new FormData(e.target),cart=getCart();if(!cart.length)return;const lines=['NEXA PRINT — SOLICITAÇÃO DE PEDIDO','',`Cliente: ${data.get('name')}`,`WhatsApp: ${data.get('phone')}`,`E-mail: ${data.get('email')||'Não informado'}`,'','ITENS:'];cart.forEach((i,n)=>{lines.push(`${n+1}. ${i.name}`);Object.entries(i.options||{}).filter(([,v])=>v).forEach(([k,v])=>lines.push(`   ${labelCart(k)}: ${v}`));lines.push(`   Quantidade: ${i.qtyLabel}`,`   Valor: ${money(i.price)}`)});lines.push('',`TOTAL: ${document.querySelector('#cartTotal')?.textContent||money(0)}`,'',`Observações: ${data.get('notes')||'Nenhuma'}`);const text=lines.join('\n');navigator.clipboard?.writeText(text).catch(()=>{});const out=document.querySelector('#orderResult');out.classList.remove('hidden');out.innerHTML='<strong>Pedido preparado.</strong><span>O resumo foi copiado. Envie-o pelo canal de atendimento da NEXA PRINT para concluir a solicitação.</span><textarea readonly></textarea>';out.querySelector('textarea').value=text});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderCart();if(new URLSearchParams(location.search).get('checkout')==='1')document.querySelector('#name')?.focus()});else renderCart();updateCartBadges();
