const NEXA_CART_KEY='nexa_print_cart_v1';
const getCart=()=>{try{return JSON.parse(localStorage.getItem(NEXA_CART_KEY)||'[]')}catch{return[]}};
const saveCart=c=>localStorage.setItem(NEXA_CART_KEY,JSON.stringify(c));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const label=k=>({size:'Tamanho',material:'Material',printing:'Impressão',finish:'Acabamento',cut_type:'Corte'})[k]||k;
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const db=window.supabase&&window.NEXA_CONFIG?window.supabase.createClient(window.NEXA_CONFIG.SUPABASE_URL,window.NEXA_CONFIG.SUPABASE_KEY):null;
function count(){return getCart().reduce((n,i)=>n+Number(i.quantity||0),0)}
function badges(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=count())}
async function resolveVariant(item){if(item.variantId)return item.variantId;if(!db)return null;const {data}=await db.from('product_variants').select('id,size,material,printing,finish,cut_type').eq('product_id',item.id).eq('is_active',true);const o=item.options||{};return (data||[]).find(v=>Object.entries(o).filter(([,x])=>x).every(([k,x])=>norm(v[k])===norm(x)))?.id||null}
async function selection(){const id=new URLSearchParams(location.search).get('id');const name=document.querySelector('#detail h1')?.textContent?.trim();const options=Object.fromEntries([...document.querySelectorAll('#variantFields select')].map(s=>[s.dataset.key,s.value]));const radio=document.querySelector('#quantities input[name="qty"]:checked');const labelText=radio?.closest('.qty')?.querySelector('.qty-left')?.textContent?.trim()||'';const m=labelText.match(/[\d.]+/);const quantity=Number((m?.[0]||'0').replace(/\./g,''));const price=Number(radio?.dataset.price||0);if(!id||!name||!quantity||!price)return null;const variantId=window.NEXA_SELECTED_VARIANT_ID||await resolveVariant({id,options});if(!variantId)return null;return {id,name,variantId,options,quantity,price,qtyLabel:labelText,key:`${id}|${variantId}|${quantity}`}}
async function add(mode){const item=await selection();if(!item){alert('Selecione a configuração e a quantidade antes de continuar.');return}const c=getCart(),i=c.findIndex(x=>x.key===item.key);if(i>=0)c[i].quantity+=item.quantity;else c.push(item);saveCart(c);badges();location.href='carrinho.html'+(mode==='buy'?'?checkout=1':'')}
document.addEventListener('click',e=>{const b=e.target.closest('#buy,#cart');if(!b)return;e.preventDefault();e.stopImmediatePropagation();add(b.id==='buy'?'buy':'cart')},true);
async function hydrate(){const c=getCart();let changed=false;for(const x of c){if(!x.variantId){x.variantId=await resolveVariant(x);changed=true}}if(changed)saveCart(c)}
function render(){const list=document.querySelector('#cartItems');if(!list)return;const c=getCart(),empty=document.querySelector('#cartEmpty'),box=document.querySelector('#checkoutBox');if(!c.length){list.innerHTML='';empty?.classList.remove('hidden');box?.classList.add('hidden');if(document.querySelector('#cartTotal'))document.querySelector('#cartTotal').textContent=money(0);if(document.querySelector('#grandTotal'))document.querySelector('#grandTotal').textContent=money(0);badges();return}empty?.classList.add('hidden');box?.classList.remove('hidden');list.innerHTML=c.map((x,n)=>`<article class="cart-item"><div><span class="eyebrow">PRODUTO</span><h3>${esc(x.name)}</h3><div class="cart-options">${Object.entries(x.options||{}).filter(([,v])=>v).map(([k,v])=>`<span>${esc(label(k))}: ${esc(v)}</span>`).join('')}</div><strong>${esc(x.qtyLabel||`${x.quantity} un`)}</strong></div><div class="cart-item-right"><strong>${money(x.price)}</strong><button class="remove-item" data-remove="${n}" type="button">Remover</button></div></article>`).join('');const subtotal=c.reduce((s,x)=>s+Number(x.price||0),0);if(document.querySelector('#cartTotal'))document.querySelector('#cartTotal').textContent=money(subtotal);updateTotal();badges()}
function updateTotal(){const subtotal=getCart().reduce((s,x)=>s+Number(x.price||0),0),sel=document.querySelector('#shippingSelect'),ship=Number(sel?.selectedOptions?.[0]?.dataset?.price||0);if(document.querySelector('#shippingTotal'))document.querySelector('#shippingTotal').textContent=sel?.value?money(ship):'A calcular';if(document.querySelector('#grandTotal'))document.querySelector('#grandTotal').textContent=money(subtotal+ship)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;const c=getCart();c.splice(Number(b.dataset.remove),1);saveCart(c);render();initCheckout()});
function authMsg(t,err=false){const x=document.querySelector('#authMessage');if(x){x.textContent=t;x.classList.toggle('error',err)}}
function authTab(tab){document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x.dataset.authTab===tab));document.querySelector('#loginForm')?.classList.toggle('hidden',tab!=='login');document.querySelector('#registerForm')?.classList.toggle('hidden',tab!=='register');authMsg('')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-auth-tab]');if(b)authTab(b.dataset.authTab)});
async function profile(){const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data:p}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();const f=document.querySelector('#orderForm');if(f){f.elements.name.value=p?.full_name||user.user_metadata?.full_name||'';f.elements.phone.value=p?.phone||user.user_metadata?.phone||'';f.elements.email.value=user.email||'';['cep','city','state','address','address_number','neighborhood','complement'].forEach(k=>{if(f.elements[k])f.elements[k].value=p?.[k]||''})}return user}
async function shipping(){const box=document.querySelector('#shippingOptions');if(!box)return;const {data}=await db.from('shipping_methods').select('*').eq('is_active',true).order('sort_order');if(!data?.length){box.textContent='Frete será calculado conforme a região e as condições de entrega.';return}box.innerHTML=`<select id="shippingSelect" class="shipping-select"><option value="" data-price="0">Escolha a forma de entrega</option>${data.map(x=>`<option value="${esc(x.id)}" data-price="${esc(x.price||0)}">${esc(x.name)} — ${money(x.price||0)}${x.deadline_days_min?` · ${esc(x.deadline_days_min)} a ${esc(x.deadline_days_max)} dias`:''}</option>`).join('')}</select>`;document.querySelector('#shippingSelect').addEventListener('change',updateTotal)}
async function initCheckout(){if(!document.querySelector('#checkoutBox')||!getCart().length||!db)return;const {data:{session}}=await db.auth.getSession();if(session){document.querySelector('#authGate')?.classList.add('hidden');document.querySelector('#customerCheckout')?.classList.remove('hidden');await profile();await shipping()}else{document.querySelector('#authGate')?.classList.remove('hidden');document.querySelector('#customerCheckout')?.classList.add('hidden')}}
document.addEventListener('submit',async e=>{if(e.target.id==='loginForm'){e.preventDefault();authMsg('Entrando…');const d=new FormData(e.target),r=await db.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});if(r.error){authMsg(r.error.message,true);return}await initCheckout();return}if(e.target.id==='registerForm'){e.preventDefault();authMsg('Criando sua conta…');const d=new FormData(e.target),r=await db.auth.signUp({email:d.get('email'),password:d.get('password'),options:{data:{full_name:d.get('full_name'),phone:d.get('phone')},emailRedirectTo:location.href}});if(r.error){authMsg(r.error.message,true);return}if(!r.data.session){authMsg('Cadastro criado. Verifique seu e-mail para confirmar a conta e depois volte para finalizar a compra.')}else{await db.from('profiles').upsert({id:r.data.user.id,full_name:d.get('full_name'),phone:d.get('phone')},{onConflict:'id'});await initCheckout()}return}if(e.target.id==='orderForm'){e.preventDefault();await order(e.target)}});
async function order(form){const {data:{session}}=await db.auth.getSession();if(!session){authTab('login');return}const c=getCart(),button=form.querySelector('.checkout-submit');button.disabled=true;button.textContent='Finalizando pedido…';try{const p={id:session.user.id,full_name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),cep:form.elements.cep.value.trim(),city:form.elements.city.value.trim(),state:form.elements.state.value.trim().toUpperCase(),address:form.elements.address.value.trim(),address_number:form.elements.address_number.value.trim(),neighborhood:form.elements.neighborhood.value.trim(),complement:form.elements.complement.value.trim()};const up=await db.from('profiles').upsert(p,{onConflict:'id'});if(up.error)throw up.error;const items=[];for(const x of c){const variantId=await resolveVariant(x);if(!variantId)throw new Error(`Não foi possível validar a configuração de ${x.name}.`);items.push({product_id:x.id,variant_id:variantId,quantity:x.quantity})}const shippingId=document.querySelector('#shippingSelect')?.value||null;const payment=form.querySelector('input[name="payment_method"]:checked')?.value||'pix';const r=await db.rpc('create_customer_order',{p_items:items,p_payment_method:payment,p_shipping_method_id:shippingId,p_notes:form.elements.notes.value.trim()||null});if(r.error)throw r.error;const o=r.data?.[0];if(!o)throw new Error('O pedido não retornou os dados esperados.');const {data:pay}=await db.from('payment_settings').select('*').eq('id',1).maybeSingle();let instruction='Os dados de pagamento ainda não foram cadastrados pela NEXA PRINT.';if(pay){if(payment==='pix'&&pay.pix_key)instruction=`<strong>PIX:</strong> ${esc(pay.pix_key)}<br>${esc(pay.account_holder||'')}`;if(payment==='bank_transfer'&&(pay.bank_name||pay.bank_account))instruction=`<strong>Banco:</strong> ${esc(pay.bank_name||'')}<br><strong>Agência:</strong> ${esc(pay.bank_agency||'')}<br><strong>Conta:</strong> ${esc(pay.bank_account||'')}<br><strong>Titular:</strong> ${esc(pay.account_holder||'')}`;if(pay.instructions)instruction+=`<br><br>${esc(pay.instructions)}`}const out=document.querySelector('#orderResult');out.classList.remove('hidden');out.innerHTML=`<h3>Pedido ${esc(o.order_number)} recebido.</h3><span>Seu pedido foi registrado no site. Pagamento: ${payment==='pix'?'PIX':'Transferência bancária'}.</span><div class="payment-instructions">${instruction}</div><strong>Total: ${money(o.total)}</strong><span>Após o pagamento, guarde o comprovante. A NEXA PRINT fará a conferência e dará andamento à produção.</span>`;saveCart([]);document.querySelector('#customerCheckout')?.classList.add('hidden');render()}catch(err){console.error(err);alert(err.message||'Não foi possível finalizar o pedido.')}finally{button.disabled=false;button.textContent='Finalizar pedido'}}
document.addEventListener('click',async e=>{if(e.target.id==='logout'){await db.auth.signOut();location.reload()}});
async function boot(){if(document.readyState==='loading')await new Promise(r=>document.addEventListener('DOMContentLoaded',r,{once:true}));await hydrate();render();if(document.querySelector('#checkoutBox'))await initCheckout();badges()}
boot();