const {createClient}=window.supabase;
const db=createClient(window.NEXA_CONFIG.SUPABASE_URL,window.NEXA_CONFIG.SUPABASE_KEY);
const id=new URLSearchParams(location.search).get('id');
const status=document.querySelector('#status'),detail=document.querySelector('#detail'),crumb=document.querySelector('#crumb');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const brl=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const ext=url=>((String(url).toLowerCase().match(/\.(cdr|ai|psd|pdf|zip|rar|7z|eps|svg)(?:$|\?)/)||[])[1]||'arquivo').toUpperCase();
const imageTag=(url,alt)=>url?`<img src="${esc(url)}" alt="${esc(alt)}" referrerpolicy="no-referrer" loading="eager" onerror="this.onerror=null;this.style.display='none';this.parentElement.querySelector('.preview-placeholder')?.classList.remove('hidden')">`:'<span class="preview-placeholder">Imagem do produto</span>';
function fail(m){status.textContent=m;status.classList.remove('hidden');detail.classList.add('hidden')}
function branding(d){if(!d)return;document.title=d.brand_name?`${d.brand_name} — Produto`:document.title;document.documentElement.style.setProperty('--primary',d.primary_color||'#19c7b5');document.documentElement.style.setProperty('--primary-dark',d.primary_color||'#0b9f91');document.documentElement.style.setProperty('--ink',d.text_color||'#102033');if(d.background_color)document.documentElement.style.setProperty('--white',d.background_color);document.body.style.fontFamily=d.body_font||'Inter,ui-sans-serif,system-ui,sans-serif';const m=document.querySelector('#brandMark');if(m&&d.logo_url)m.outerHTML=`<img id="brandMark" class="brand-logo" src="${esc(d.logo_url)}" alt="${esc(d.brand_name||'NEXA PRINT')}" referrerpolicy="no-referrer">`;const f=document.querySelector('#footerBrand');if(f&&d.brand_name)f.textContent=d.brand_name}
async function loadTemplates(variantId){const box=document.querySelector('#templateList');box.innerHTML='<div class="muted">Carregando gabaritos…</div>';const {data:links,error:e1}=await db.from('variant_templates').select('template_id,sort_order').eq('variant_id',variantId).order('sort_order');if(e1){console.error(e1);box.innerHTML='<div class="muted">Não foi possível carregar os gabaritos.</div>';return}const ids=[...(links||[])].map(x=>x.template_id).filter(Boolean);if(!ids.length){box.innerHTML='<div class="muted">Nenhum gabarito cadastrado para esta configuração.</div>';return}const {data:ts,error:e2}=await db.from('templates').select('id,template_url,template_type,title,file_name').in('id',ids);if(e2){console.error(e2);box.innerHTML='<div class="muted">Não foi possível carregar os gabaritos.</div>';return}const map=new Map((ts||[]).map(t=>[t.id,t]));
const seenTypes=new Set();
const uniqueTemplates=ids.map(x=>map.get(x)).filter(Boolean).filter(t=>{const type=norm(t.template_type||ext(t.template_url));if(seenTypes.has(type))return false;seenTypes.add(type);return true});
box.innerHTML=uniqueTemplates.map(t=>{const u=t.template_url||'';return `<a class="template-link" href="${esc(u)}" target="_blank" rel="noopener noreferrer"><span class="template-icon">${esc(ext(u).slice(0,4))}</span><span class="template-copy"><strong>${esc(t.title||t.template_type||ext(u))}</strong><span>Baixar gabarito</span></span><span class="template-ext">${esc(ext(u))}</span></a>`}).join('')||'<div class="muted">Nenhum gabarito cadastrado para esta configuração.</div>'}
async function load(){if(!id)return fail('Produto não informado.');const [{data:p,error:pe},{data:s}]=await Promise.all([db.from('products').select('*').eq('id',id).maybeSingle(),db.from('site_settings').select('*').eq('id',1).maybeSingle()]);if(s)branding(s);if(pe||!p)return fail('Produto não encontrado.');const {data:variants,error:ve}=await db.from('product_variants').select('*').eq('product_id',id).eq('is_active',true).order('size');if(ve)return fail('Não foi possível carregar as configurações.');const {data:images}=await db.from('product_images').select('*').eq('product_id',id).order('is_primary',{ascending:false}).order('sort_order');const cat=p.category_id?(await db.from('categories').select('name').eq('id',p.category_id).maybeSingle()).data:null;status.classList.add('hidden');detail.classList.remove('hidden');if(crumb)crumb.innerHTML=`<a href="index.html">Início</a> / ${cat?.name?esc(cat.name)+' / ':''}${esc(p.name)}`;const previewUrl=images?.[0]?.image_url||p.image_url||'';detail.innerHTML=`<section class="panel"><span class="eyebrow">${esc(cat?.name||'PRODUTO')}</span><h1>${esc(p.name)}</h1>${p.short_description?`<p class="muted">${esc(p.short_description)}</p>`:''}<div class="divider"></div><div class="configuration-block"><h3>1. Configure o produto</h3><div class="config-grid" id="variantFields"></div></div><div class="divider"></div><div class="configuration-block"><h3>2. Escolha a quantidade</h3><div id="quantities" class="quantity-list"><div class="muted">Escolha todas as opções acima.</div></div></div><div class="divider"></div><div class="templates"><span class="eyebrow">GABARITOS DE ARTE</span><div class="section-title">Baixe o modelo correto antes de montar sua arte.</div><div class="templates-note">Os arquivos correspondem à configuração selecionada.</div><div id="templateList" class="template-list"><div class="muted">Selecione a configuração.</div></div></div></section><aside class="panel buy-card"><div class="preview">${previewUrl?`${imageTag(previewUrl,p.name)}<span class="preview-placeholder hidden">Imagem do produto</span>`:'<span class="preview-placeholder">Imagem do produto</span>'}</div><div class="price-label">VALOR DA CONFIGURAÇÃO</div><div id="total" class="total">Selecione uma quantidade</div><div class="buy-actions"><button class="btn btn-primary" id="buy">Comprar agora</button><button class="btn btn-light" id="cart">Adicionar ao carrinho</button></div></aside></section>`;
const values={size:new Set(),material:new Set(),printing:new Set(),finish:new Set(),cut_type:new Set()};(variants||[]).forEach(v=>Object.keys(values).forEach(k=>v[k]&&values[k].add(v[k])));const labels={size:'Tamanho',material:'Material',printing:'Impressão / Cor',finish:'Cobertura / Acabamento',cut_type:'Corte'};const keys=Object.keys(values).filter(k=>values[k].size);document.querySelector('#variantFields').innerHTML=keys.map(k=>`<div class="field"><label>${labels[k]}</label><select data-key="${k}"><option value="">Escolha</option>${[...values[k]].map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></div>`).join('');
async function refresh(){const wanted={};document.querySelectorAll('#variantFields select').forEach(s=>wanted[s.dataset.key]=norm(s.value));if(keys.some(k=>!wanted[k])){document.querySelector('#quantities').innerHTML='<div class="muted">Escolha todas as opções acima.</div>';document.querySelector('#templateList').innerHTML='<div class="muted">Selecione a configuração completa para consultar os gabaritos.</div>';document.querySelector('#total').textContent='Selecione uma quantidade';return}const v=(variants||[]).find(x=>keys.every(k=>norm(x[k])===wanted[k]));if(!v){document.querySelector('#quantities').innerHTML='<div class="muted">Essa combinação não está disponível.</div>';document.querySelector('#templateList').innerHTML='<div class="muted">Nenhum gabarito para essa combinação.</div>';document.querySelector('#total').textContent='Configuração indisponível';return}const {data:prices}=await db.from('variant_prices').select('*').eq('variant_id',v.id).order('quantity');const q=document.querySelector('#quantities');q.innerHTML=(prices||[]).map((x,i)=>`<label class="qty ${i===0?'active':''}"><span class="qty-left"><input type="radio" name="qty" data-price="${esc(x.selling_price)}" ${i===0?'checked':''}> ${esc(x.quantity)} ${esc(x.unit_suffix||'un')}</span><span class="qty-price">${brl(x.selling_price)}</span></label>`).join('')||'<div class="muted">Sem quantidades cadastradas.</div>';const first=q.querySelector('input');if(first)document.querySelector('#total').textContent=brl(first.dataset.price);q.querySelectorAll('input').forEach(r=>r.onchange=()=>{q.querySelectorAll('.qty').forEach(z=>z.classList.remove('active'));r.closest('.qty')?.classList.add('active');document.querySelector('#total').textContent=brl(r.dataset.price)});await loadTemplates(v.id)}
document.querySelectorAll('#variantFields select').forEach(s=>s.onchange=refresh);document.querySelector('#buy').onclick=()=>alert('Checkout será conectado na próxima etapa.');document.querySelector('#cart').onclick=()=>alert('Carrinho será conectado na próxima etapa.')}
load().catch(e=>{console.error(e);fail('Erro ao carregar o produto.')});
